# Generated by Django 4.0.3 on 2022-03-17 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangorestAPI', '0003_hobby_delete_personaldetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hobby',
            name='id',
        ),
        migrations.AlterField(
            model_name='hobby',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='djangorestAPI.student'),
        ),
    ]
