# Generated by Django 4.0.3 on 2022-03-17 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangorestAPI', '0004_remove_hobby_id_alter_hobby_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='hobby',
            name='id',
            field=models.BigAutoField(auto_created=True, default=900, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hobby',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangorestAPI.student'),
        ),
    ]
