# Generated by Django 4.0.3 on 2022-03-17 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangorestAPI', '0005_hobby_id_alter_hobby_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hobby',
            name='student',
        ),
        migrations.AddField(
            model_name='student',
            name='hobies',
            field=models.ManyToManyField(related_name='hobbys', to='djangorestAPI.hobby'),
        ),
    ]
